# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: image classification with ONNX

on:
  pull_request:
    branches: [ "main", "dev", "mlperf-inference" ]
    paths:
      - '.github/workflows/test-image-classification-onnx.yml'
      - '**'
      - '!**.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [ "3.10", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Configure git longpaths (Windows)
      if: matrix.os == 'windows-latest'
      run: |
        git config --system core.longpaths true
    - name: Install cm4mlops on Windows
      if: matrix.os == 'windows-latest'
      run: |
        $env:CM_PULL_DEFAULT_MLOPS_REPO = "no"; pip install cm4mlops
    - name: Install dependencies on Unix Platforms
      if: matrix.os != 'windows-latest'
      run: |
        CM_PULL_DEFAULT_MLOPS_REPO=no pip install cm4mlops
    - name: Pull MLOps repository
      run: |
        cm pull repo --url=${{ github.event.pull_request.head.repo.html_url }} --checkout=${{ github.event.pull_request.head.ref }}
        cm run script --quiet --tags=get,sys-utils-cm
    - name: Test image classification with ONNX
      run: |
        cm run script --tags=python,app,image-classification,onnx --quiet
